### ISSUE TITLE
Environment crashes after installing compilers on windows

### ISSUE THREAD

**Issue by santiagoropb** [conda-forge/compilers-feedstock#10]
Issue:
I would like to try gcc from a conda environment on Windows. However, when I conda install -c conda-forge compilers the environment crashes. Is there any dependency that has to be install on windows before installing compilers? After installation every time I try to activate the environment the conda promt crashes.
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
conda version 4.6.14
python version 3.7.3.final.0
platform win-64
OS Windows 10
```
</details>

**Comment by scopatz** [comment]
Hmm this seems like it should be brought up with Anaconda. This package actually doesn't do anything on Windows
