### ISSUE TITLE
Use compilers to build a package using OpenMP on MacOS

### ISSUE THREAD

**Issue by jeremiedbb** [conda-forge/compilers-feedstock#15]
Hi,

On macOS, the default clang compiler does not directly support OpenMP, so I'm trying to use `compilers`.
When installing compilers, I can find OpenMP headers in `<conda path>/envs/<my env>/include`
and OpenMP runtime in `<conda path>/envs/<my env>/lib`.

To be able to compile I have to set the following:
```
CFLAGS="$CFLAGS -I<path to omp.h>"
LDFLAGS="$LDFLAGS -L<path to libomp.dylib> -Wl,rpath,<path to libomp.dylib>"
```

First, is this the recommended way to proceed ?

Then, since installing compilers sets a bunch of environment variables like `CC`, `CFLAGS`, `LDFLAGS`, ... I was wondering if it would made sense to also add the previous include and link flags. Is there a reason not to add them ?

Thanks

cc @ogrisel @jakirkham

**Comment by lesteve** [comment]
@jeremiedbb if you don't get any answer in the next few days, I would suggest you try posting on the conda-forge gitter (`conda-forge/conda-forge.github.io) and linking to this issue with a short summary.

**Comment by scopatz** [comment]
Or do you have a recipe we can look at?

**Comment by adrinjalali** [comment]
@scopatz we have a recipe here: https://github.com/conda-forge/scikit-learn-feedstock

**Comment by jakirkham** [comment]
I'm not surprised you might need these flags. Though have no thoughts on whether the `compilers` package should set these by default or leave them up to the user. @conda-forge/compilers, would you be able to weigh in here?

**Comment by jakirkham** [comment]
Also @mingwandroid do you have any thoughts on baking these into the Anaconda compilers?

**Comment by mingwandroid** [comment]
Our compilers do support OpenMP and they do so transparently (well, you pass -fopenmp, but that's the job of the build system to detect and perform).

From our side we simply add `llvm-openmp` as a build and host (and maybe a run dependency depending on run_exports) dependency and everything should just work. Here is an example: https://github.com/AnacondaRecipes/r-data.table-feedstock/tree/master/recipe

I hope one day to change it so you do not need it in all these places, but finding the time is difficult.

**Comment by adrinjalali** [comment]
The issue is not how to have the recipe handle openmp, we already have that working in our recipe as well. The question is, how can we setup an environment with conda, and conda compilers, so that `python setup.py build_ext` would work.

https://github.com/scikit-learn/scikit-learn/issues/14905#issuecomment-528933415 shows the issue when the environment variables are not properly set.

**Comment by jakirkham** [comment]
IIUC it works, but one needs to set environment variables and you would like to avoid that, correct? If not, we still need to figure out the working environment variable settings.

If so the question becomes where to bake the working configuration you’ve found into. Here are the options I see. Please feel free to suggest others.

1. Anaconda compilers
2. This `compilers` package
3. Nowhere, but we document things

Thoughts on these options?

**Comment by adrinjalali** [comment]
I was also told that installing the `llvm-openmp` package instead of brew installing `libomp` may just work. I still need to check that.

**Comment by jeremiedbb** [comment]
@jakirkham Ideally what we'd like is to be able to build scikit-learn from source using the conda-forge compilers package (this would be the easiest way for our contributors on macOS). In other words:
```
conda install numpy scipy joblib cython  # scikit-learn dependencies
conda install -c conda-forge compilers
python setup.py build_ext -i
```
(We do set `-fopenmp` as extra-compile/link flags in scikit-learn setup.py)

Currently this doesn't work as is. We need to set
```
CFLAGS="$CFLAGS -I<path to omp.h>"
LDFLAGS="$LDFLAGS -L<path to libomp.dylib> -Wl,rpath,<path to libomp.dylib>"
```
The second one maybe unnecessary, I need to confirm that.
However the first one is for sure necessary.

And even with that, we still have some linking issues:
```
warning: ranlib: warning for library: build/temp.macosx-10.9-x86_64-3.7/liblibsvm-skl.a the table of contents is empty (no object file members in the library define global symbols)
```
Even if it's a warning, the executable is broken because of that. I've no idea what's going on...

**Comment by mingwandroid** [comment]
If people want to use our compilers without needing with command line parameters they need to set CONDA_BUILD before activating the env. After that CFLAGS etc can be used.

I explicitly do not want to force these flags on anyone who wants to use or compilers but not our package ecosystem.

**Comment by mingwandroid** [comment]
-fopemp is all you need once things are setup correctly.

**Comment by mingwandroid** [comment]
For ranlib you need to use ours and not the system one. This means using our linker and not the system one usually.

**Comment by jakirkham** [comment]
Would retest in light of PR ( https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/2 ).

**Comment by jeremiedbb** [comment]
Thanks everyone. It's indeed working as expected now.

**Comment by jakirkham** [comment]
Thanks for confirming @jeremiedbb! 😄
