### ISSUE TITLE
System ranlib is used instead of conda-forge::compilers on the conda-forge infrastructure on macOS with Pyhon 3.7

### ISSUE THREAD

**Issue by ogrisel** [conda-forge/compilers-feedstock#19]
This problem is specific to the conda-forge CI infrastructure and cannot be reproduced locally. It was discovered on this scikit-learn-feedstock PR:

https://github.com/conda-forge/scikit-learn-feedstock/pull/115#issuecomment-570254995

I am not sure if this is the right place to report it. Feel free to close this issue and let me know where to report the problem.

**Comment by scopatz** [comment]
Hi @ogrisel - unfortunately, this is just a convience package for users to get the compilers, and is not a good place to report issues.  I would recommend reporting on the conda-forge.github.io repo
