### ISSUE TITLE
clang -fopenmp depends on openmp

### ISSUE THREAD

**Issue by cbworden** [conda-forge/compilers-feedstock#21]
Issue:
Please see the thread at: https://github.com/conda-forge/clangdev-feedstock/issues/98#issuecomment-634876987

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

Please see the thread at: https://github.com/conda-forge/clangdev-feedstock/issues/98#issuecomment-634876987

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

Please see the thread at: https://github.com/conda-forge/clangdev-feedstock/issues/98#issuecomment-634876987

```
</details>

**Comment by chrisburr** [comment]
I think this is fixed by #22
