### ISSUE TITLE
binutils installs wrong version

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/compilers-feedstock#3]
Currently running `conda install binutils` installs the version from before the compiler migration as the version is `2.32` and this metapackage is `1.0.0`. Is this what we want or should using `binutils-feedstock` be deprecated?

Related: Currently `gcc` and `ld` can get out of sync as only `compilers` pins `binutils` with `exact=True`, `c-compiler`/`cxx-compiler`/`fortran-compiler` should as well. I'll make a PR to fix this in a moment.

**Comment by scopatz** [comment]
We should not have a metapackage of binutils with a different version number.  This is a mistake in my opinion.

**Comment by isuruf** [comment]
`binutils` meta package was removed from here
