### ISSUE TITLE
Conda forge packages built against libgcc-ng >=12 and libstdcxx-ng >=12

### ISSUE THREAD

**Issue by Jaynor** [conda-forge/compilers-feedstock#48]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It looks like packages that were built after mid-May of 2022 depend on `libgcc-ng >=12` and `libstdcxx-ng >=12` (For example `numpy==1.22.4`) However, the latest `gcc_linux-64` and `gxx_linux-64` on Conda-forge is `11.2.0`. Now, my team is facing issues/conflicts with the GCC version and other new packages. Do you guys have plans to release GCC>=12 anytime soon? 

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by isuruf** [comment]
Can you give a reproducer for issues/conflicts?

**Comment by isuruf** [comment]
It should be possible to install `gcc_linux-64=11` alongside `libgcc-ng=12` and `libstdcxx-ng`. So it's puzzling to me how there can be conflicts.

I opened https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/79 to update `gcc_linux-64` to `12.1.0`

**Comment by Jaynor** [comment]
The issue is not obvious on the surface, but it has an underline issue. I can create an environment with `numpy=1.22.4`(along with `libgcc-ng >=12` and `libstdcxx-ng >=12`)with `gcc_linux-64=11.2.0`. However, library and compiler mismatch can create issues with our C++ native packages with other Python packages.

**Comment by isuruf** [comment]
Ok. I'll be interested to know what the library and compiler mismatch are and if we can mitigate that. I believe Ubuntu/debian does the same with `gcc=11` being the default and `libstdcxx=12`.

Hopefully the above PR can fix the issue for you.

**Comment by mattgodbolt** [comment]
> ... I believe Ubuntu/debian does the same with gcc=11 being the default and libstdcxx=12.

Hi! Maybe's it's a bit of superstition on my part, but having debugged enough cross-library woes I'm super sensitive to any kind of system library mismatch. I know C++ is famous for never wanting to break ABI, but pragmatically I've had issues before (notably; things like one `.so` throwing an exception caught in another...). _Maybe_ it's ok but we've always tried to have a consistent set of libraries and compilers. This [post](https://news.ycombinator.com/item?id=9780871#:~:text=Two%20C%2B%2B%20ABIs-,GCC%20libstdc%2B%2B%20has%20been%20backward%20compatible%20with%20no%20ABI,GCC4%20over%20the%20last%20decade.) post seems to say it's ok, so perhaps this is all a storm in a teacup.

That said: if we can have a gcc-12 package that activates and lets us build our own code easily against gcc 12, then even better :)

**Comment by isuruf** [comment]
Updated in https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/79. `gcc_linux-64=12` should be available in around 2 hours.
