### ISSUE TITLE
compiler('fortran') does not provide `gfortran` command

### ISSUE THREAD

**Issue by nicogodet** [conda-forge/compilers-feedstock#70]
### Comment:

I maintain the `opentelemac` package on conda and I ran into an issue or ignorance...

opentelemac requieres a fortran compiler and use mpif90 to compile fortran code.
opentelemac use meson (through f2py) to compile a Fortran API for Python and on first attempt, meson was not able to find a fortran compiler : https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1089700&view=logs&j=d93976e3-6ed1-588b-ebf8-e8a19c2becc4&t=90b382e2-e6d3-5178-8133-a486ee34063f&l=8516
while compiler('fortran') is specified in [meta.yml](https://github.com/conda-forge/opentelemac-feedstock/blob/main/recipe/meta.yaml)

In test env, I installed `gfortran_linux-64` which seems provided by compiler('fortran') : https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1090724&view=logs&j=d93976e3-6ed1-588b-ebf8-e8a19c2becc4&t=90b382e2-e6d3-5178-8133-a486ee34063f&l=637
and indeed `$ gfortran` returns `-bash: gfortran: command not found`
If I install `gfortran`, above command is OK.

So my questions are: is it a normal behavior ? Am I missing something ?

**Comment by nicogodet** [comment]
`conda create -n fortran fortran-compiler` provides `gfortran` command (`gfortran           conda-forge/linux-64::gfortran-13.3.0-h9576a4e_1`) but this is not what is installed in CI when building opentelemac

**Comment by duncanmmacleod** [comment]
@nicogodet, I'm not a fortran expert (or even close), but the issue _might_ be that the compilers are currently specified in your `requirements:host` list, whereas I think they should be in the `requirements:build` list. See https://conda-forge.org/docs/maintainer/adding_pkgs/#build-1.

It looks like the MR for the failed build was merged, so I presume you worked around the problem.

**Comment by nicogodet** [comment]
See linked issue, moving compiler() in build section results in same issue: gfortran command not found

**Comment by nicogodet** [comment]
Add gfortran explicitly solves the issue

**Comment by isuruf** [comment]
We set `FC` env variable to `x86_64-conda-linux-gnu-gfortran` and build systems should use the value of `FC` env var instead of relying on a gfortran command. If the build system does not support it, I suggest you patch the build system.
